const TRANSLATIONS_ALPHABET = {
    "alphabet_title": {
        en: "German Alphabet",
        de: "Deutsches Alphabet",
        cs: "Německá abeceda",
        pl: "Alfabet niemiecki",
        da: "Tysk alfabet",
        uk: "Німецький алфавіт"
    },
    "back_to_menu": {
        en: "Back to Menu",
        de: "Zurück zum Menü",
        cs: "Zpět do menu",
        pl: "Powrót do menu",
        da: "Tilbage til menuen",
        uk: "Назад до меню"
    },
    "a_pron": { en: "[a]", de: "[a]", cs: "[a]", pl: "[a]", da: "[a]", uk: "[а]" },
    "b_pron": { en: "[be]", de: "[be]", cs: "[be]", pl: "[be]", da: "[be]", uk: "[бе]" },
    "c_pron": { en: "[tse]", de: "[tse]", cs: "[ce]", pl: "[ce]", da: "[tse]", uk: "[це]" },
    "d_pron": { en: "[de]", de: "[de]", cs: "[de]", pl: "[de]", da: "[de]", uk: "[де]" },
    "e_pron": { en: "[e]", de: "[e]", cs: "[e]", pl: "[e]", da: "[e]", uk: "[е]" },
    "f_pron": { en: "[ef]", de: "[ef]", cs: "[ef]", pl: "[ef]", da: "[ef]", uk: "[еф]" },
    "g_pron": { en: "[ge]", de: "[ge]", cs: "[ge]", pl: "[ge]", da: "[ge]", uk: "[ге]" },
    "h_pron": { en: "[ha]", de: "[ha]", cs: "[ha]", pl: "[ha]", da: "[ha]", uk: "[ха]" },
    "i_pron": { en: "[i]", de: "[i]", cs: "[i]", pl: "[i]", da: "[i]", uk: "[і]" },
    "j_pron": { en: "[yot]", de: "[jot]", cs: "[jot]", pl: "[jot]", da: "[jot]", uk: "[йот]" },
    "k_pron": { en: "[ka]", de: "[ka]", cs: "[ka]", pl: "[ka]", da: "[ka]", uk: "[ка]" },
    "l_pron": { en: "[el]", de: "[el]", cs: "[el]", pl: "[el]", da: "[el]", uk: "[ель]" },
    "m_pron": { en: "[em]", de: "[em]", cs: "[em]", pl: "[em]", da: "[em]", uk: "[ем]" },
    "n_pron": { en: "[en]", de: "[en]", cs: "[en]", pl: "[en]", da: "[en]", uk: "[ен]" },
    "o_pron": { en: "[o]", de: "[o]", cs: "[o]", pl: "[o]", da: "[o]", uk: "[о]" },
    "p_pron": { en: "[pe]", de: "[pe]", cs: "[pe]", pl: "[pe]", da: "[pe]", uk: "[пе]" },
    "q_pron": { en: "[ku]", de: "[ku]", cs: "[ku]", pl: "[ku]", da: "[ku]", uk: "[ку]" },
    "r_pron": { en: "[er]", de: "[er]", cs: "[er]", pl: "[er]", da: "[er]", uk: "[ер]" },
    "s_pron": { en: "[es]", de: "[es]", cs: "[es]", pl: "[es]", da: "[es]", uk: "[ес]" },
    "t_pron": { en: "[te]", de: "[te]", cs: "[te]", pl: "[te]", da: "[te]", uk: "[те]" },
    "u_pron": { en: "[u]", de: "[u]", cs: "[u]", pl: "[u]", da: "[u]", uk: "[у]" },
    "v_pron": { en: "[fao]", de: "[fau]", cs: "[fau]", pl: "[fau]", da: "[fau]", uk: "[фау]" },
    "w_pron": { en: "[ve]", de: "[ve]", cs: "[ve]", pl: "[we]", da: "[ve]", uk: "[ве]" },
    "x_pron": { en: "[iks]", de: "[iks]", cs: "[iks]", pl: "[iks]", da: "[iks]", uk: "[ікс]" },
    "y_pron": { en: "[ypsilon]", de: "[ypsilon]", cs: "[ypsilon]", pl: "[ypsilon]", da: "[ypsilon]", uk: "[іпсілон]" },
    "z_pron": { en: "[tset]", de: "[tset]", cs: "[cet]", pl: "[cet]", da: "[tset]", uk: "[цет]" },
    "ae_pron": { en: "[a-Umlaut]", de: "[a-Umlaut]", cs: "[a-Umlaut]", pl: "[a-Umlaut]", da: "[a-Umlaut]", uk: "[а-умлаут]" },
    "oe_pron": { en: "[o-Umlaut]", de: "[o-Umlaut]", cs: "[o-Umlaut]", pl: "[o-Umlaut]", da: "[o-Umlaut]", uk: "[о-умлаут]" },
    "ue_pron": { en: "[u-Umlaut]", de: "[u-Umlaut]", cs: "[u-Umlaut]", pl: "[u-Umlaut]", da: "[u-Umlaut]", uk: "[у-умлаут]" },
    "ss_pron": { en: "[Eszett]", de: "[Eszett]", cs: "[Eszett]", pl: "[Eszett]", da: "[Eszett]", uk: "[есцет]" }
};
